using FeedbackReviewer.Models;
using FeedbackReviewer.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace FeedbackReviewer.Controllers
{
    [RoutePrefix("api/employees")]
    public class EmployeesController : ApiController
    {
        public IEmployeeDataService _employeeDataService;

        public EmployeesController()
        {
            _employeeDataService = new EmployeeDataService();
        }

        /// <summary>
        /// Get all the employees on the system.
        /// </summary>
        /// <returns></returns>
        [Route("")]
        [HttpGet]
        public List<Employee> GetEmployees()
        {
            return _employeeDataService.GetAllEmployees();
        }

        /// <summary>
        /// Get an employee by their employeeId
        /// </summary>
        /// <param name="EmployeeId"></param>
        /// <returns></returns>
        [Route("{EmployeeId:Guid}")]
        [HttpGet]
        public Employee Get(Guid employeeId)
        {
            return _employeeDataService.GetEmployee(employeeId);
        }

        /// <summary>
        /// Create a new employee
        /// </summary>
        /// <param name="employee"></param>
        /// <remarks>EmployeeId will be generated by the service and returned in the response.</remarks>
        /// <returns></returns>
        [Route("")]
        [HttpPost]
        public Employee Post(Employee employee)
        {
            return _employeeDataService.AddEmployee(employee);
        }

        /// <summary>
        /// Update an employees details
        /// </summary>
        /// <param name="employeeId"></param>
        /// <param name="employee"></param>
        /// <returns></returns>
        [Route("{EmployeeId:Guid}")]
        [HttpPut]
        public Employee Put(Guid employeeId, Employee employee)
        {
            return _employeeDataService.UpdateEmployee(employeeId, employee);
        }

        /// <summary>
        /// Delete an employee from the system
        /// </summary>
        /// <param name="employeeId"></param>
        [Route("{EmployeeId:Guid}")]
        [HttpDelete]
        public void Delete(Guid employeeId)
        {
            _employeeDataService.DeleteEmployee(employeeId);
        }
    }
}
