using FeedbackReviewer.Models;
using FeedbackReviewer.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace FeedbackReviewer.Controllers
{
    [RoutePrefix("api/performancereviews")]
    public class PerformanceReviewController : ApiController
    {
        public IPerformanceReviewDataService _performanceReviewDataService;

        public PerformanceReviewController()
        {
            _performanceReviewDataService = new PerformanceReviewDataService();
        }

        /// <summary>
        /// Get all performance reviews in the system.
        /// </summary>
        /// <returns></returns>
        [Route("")]
        [HttpGet]
        public List<PerformanceReview> GetAll()
        {
            return _performanceReviewDataService.GetAllPerformanceReviews();
        }

        /// <summary>
        /// Get a single performance review by performanceReviewId
        /// </summary>
        /// <param name="performanceReviewId"></param>
        /// <returns></returns>
        [Route("{performanceReviewId:Guid}")]
        [HttpGet]
        public PerformanceReview Get(Guid performanceReviewId)
        {
            return _performanceReviewDataService.GetPerformanceReview(performanceReviewId);
        }

        /// <summary>
        /// Create a new performance review
        /// </summary>
        /// <param name="performanceReview"></param>
        /// <remarks>
        /// PerformanceReviewId will be generated by the system and returned in the response.
        /// </remarks>
        /// <returns></returns>
        [Route("")]
        [HttpPost]
        public PerformanceReview Post(PerformanceReview performanceReview)
        {
            return _performanceReviewDataService.AddPerformanceReview(performanceReview);
        }

        /// <summary>
        /// Update a performance review with feedback
        /// </summary>
        /// <param name="performanceReviewId"></param>
        /// <param name="performanceReview"></param>
        /// <returns></returns>
        [Route("")]
        [HttpPut]
        public PerformanceReview Update(Guid performanceReviewId, string feedback)
        {
            return _performanceReviewDataService.UpdatePerformanceReview(performanceReviewId, feedback);
        }
    }
}
